const $=s=>document.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={deals:[],cat:'Tous',savedOnly:false,settings:{launch:false,staleDays:3},source:'fallback',lastFocus:null};
const qp=k=>new URLSearchParams(location.search).get(k)||'';
const safe=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const euro=n=>new Intl.NumberFormat('fr-BE',{style:'currency',currency:'EUR'}).format(Number(n)||0);
function saved(){try{return JSON.parse(localStorage.getItem('fd_saved')||'[]').map(Number)}catch{return[]}}function saveIds(a){localStorage.setItem('fd_saved',JSON.stringify(a));updateFavCount()}function toggleSave(id){let a=saved();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];saveIds(a);render()}
function updateFavCount(){const n=saved().length;$$('[data-fav-count]').forEach(x=>x.textContent=n?` ${n}`:'')}
function isExpired(d){if(!d.expires)return false;const t=new Date(d.expires+'T23:59:59').getTime();return Number.isFinite(t)&&t<Date.now()}
async function loadDeals(){try{const r=await fetch('/api/deals',{cache:'no-store'});if(r.ok){const j=await r.json();if(Array.isArray(j.deals)){state.deals=j.deals;return}}}catch{}try{const r=await fetch('/deals.json',{cache:'no-store'});if(r.ok)state.deals=(await r.json()).filter(d=>(d.status||'active')==='active')}catch{}}
function imageBlock(d){return `<div class="product-media">${d.image_url?`<img loading="lazy" src="${safe(d.image_url)}" alt="${safe(d.name)}">`:''}</div>`}
function filtered(){return state.deals.filter(d=>!isExpired(d)&&(!state.cat||state.cat==='Tous'||d.cat===state.cat)).sort((a,b)=>Number(b.discount)-Number(a.discount))}
function render(){const grid=$('#grid');if(!grid)return;const a=filtered(),fav=saved();$('#count').textContent=`${a.length} résultat${a.length>1?'s':''}`;$('#empty').style.display=a.length?'none':'block';grid.innerHTML=a.map(d=>`<article class="deal-card">${imageBlock(d)}<div class="card-body"><div class="card-kicker"><strong>${safe(d.brand)}</strong><span>${safe(d.cat)}</span></div><div class="card-title">${safe(d.name)}</div><div class="price-line"><div><span class="price">${euro(d.price)}</span><span class="old">${euro(d.old)}</span></div><span class="discount-pill">-${Number(d.discount)}%</span></div><div class="merchant-line"><strong>${safe(d.merchant)}</strong></div><div class="card-buttons"><a class="deal-cta" href="/out/${encodeURIComponent(d.id)}">Voir chez ${safe(d.merchant)}</a><button type="button" class="heart ${fav.includes(d.id)?'saved':''}" data-save="${Number(d.id)}">♡</button></div></div></article>`).join('');$$('[data-save]').forEach(b=>b.onclick=()=>toggleSave(Number(b.dataset.save)))}
function bind(){$$('[data-explore]').forEach(b=>b.onclick=()=>$('#grid')?.scrollIntoView({behavior:'smooth'}));$$('[data-open-saved]').forEach(b=>b.onclick=()=>{state.savedOnly=!state.savedOnly;render()})}
async function load(){await loadDeals();bind();render();updateFavCount();const d=filtered()[0];if(d){$('#heroProduct').textContent=d.name;$('#heroBrand').textContent=`${d.brand} · ${d.cat}`;$('#heroPrice').textContent=euro(d.price);$('#heroDiscount').textContent=`-${d.discount}%`;$('#heroOld').textContent=euro(d.old)}}
load();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(()=>{}));